AY2324S1-CS2103T-T14-2/tp

docs/team/wujy28.md

Not all team members have uploaded their AboutUs.md images and PPP documents.
Each member should upload their respective documents.
Let's add the AboutUs.md image and PPP for wujy28.

Add AboutUs.md image and PPP

---

README.md
docs/AboutUs.md
docs/DeveloperGuide.md
docs/UserGuide.md
docs/index.md

There are currently some formatting bugs in documentation like the README, AboutUs, DG, UG and index. Bugs include invalid hyperlinks, random symbols, inconsistent headings and grammatical errors.
Fixing these issues can help our documentation come across as more professional and proper.
Let's
* Fix grammatical issues
* Standardize heading capitalization
* Contextual important parts of the docs to our project
* Fix hyperlink errors

Fix documentation formatting issues

---

src/main/java/seedu/address/model/patient/Age.java
src/main/java/seedu/address/model/patient/Gender.java
src/test/java/seedu/address/model/patient/AgeTest.java
src/test/java/seedu/address/model/patient/GenderTest.java

1. Added Age class
2. Added AgeTest class
3. Added Gender class
4. Added GenderTest class

Add Age and Gender Attributes

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/patient/UniquePatientList.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java

Update Add command to allow required and optional fields
1.Wrote getPrefixesPresent function that takes in argMultimap and return list of prefixes present
2.Wrote testcases for getPrefixesPresent function.
1.Wrote createPatientFromPrefixes function thats takes in list of prefixes and argMultimap and return a Patient. If field is missing, default value is used.
2.Wrote testcases for createPatientFromPrefixes.
1.Wrote testcase for duplicate prefixes
1.Create message that is output when required field is absent from user input.

Update Add Command to allow required and optional fields

---

src/main/java/seedu/address/model/patient/AssignedDepartment.java
src/main/java/seedu/address/model/patient/Department.java
src/main/java/seedu/address/model/patient/Gender.java
src/test/java/seedu/address/model/patient/AssignedDepartmentTest.java
src/test/java/seedu/address/model/patient/DepartmentTest.java

Added the Department enum and AssignedDepartment class to the model so that Patient can store
their assigned department as an attribute in the future.
1. Added the class as an attribute to Patient
2. Conducted unit testing on methods in the class
1. Added the enumeration to store accepted values for departments in the hospital
2. Wrote unit tests for the enumeration
1. Fix the trailing whitespace issue in the Gender class

Add Department Enum and AssignedDepartment Class

---

src/main/java/seedu/address/model/patient/IcNumber.java
src/test/java/seedu/address/model/patient/IcNumberTest.java

Make IcNumber attribute case insensitive

Minor modifications to IcNumber and IcNumberTest

---

src/main/java/seedu/address/model/patient/Record.java
src/test/java/seedu/address/model/patient/RecordTest.java
src/test/java/seedu/address/testutil/RecordBuilder.java

Remove the visitedDepartment variable from the class. Add some JUnit test cases suggested by teammates.

Update Record.java and RecordTest.java

---

src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/model/patient/Patient.java

Edited Patient class and CliSyntax class to include new attributes
1. Added fields for new attributes
2. Changed constructor
3. Added methods to get new attributes
4. Edited equals, hashCode, toString methods
1. Added prefixes for new attributes
2. Added prefixes for editing record

Edit Patient and CliSyntax classes to include new attributes

---

src/main/java/seedu/address/model/patient/Patient.java
src/main/java/seedu/address/model/patient/Record.java
src/main/java/seedu/address/storage/JsonAdaptedPatient.java

Integrate storage to UI so that assignedDepartment field can be displayed on UI
---
1.Update JsonAdaptedPatient to read the JSON field of assignedDepartment
1.Create a new constructor for Patient class that will allow assignedDepartment to be a parameter

Integrate assignedDepartment display

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/patient/Record.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
src/test/java/seedu/address/testutil/PatientBuilder.java
src/test/java/seedu/address/testutil/TypicalPatients.java

Mainly updating some testing utilities to fit the new Patient attributes
---
1. Added valid/invalid fields for test Patients
1. Update to build new PatientDescriptor with new Patient fields
1. Update to build new PatientDescriptor with new Patient fields
1. Add new method `withDefaultValue()` which allows PatientBuilder to be built with default values
1. Created new testing methods for AddCommandParser.java

Update testing utilities with new Patient attributes

---

docs/UserGuide.md

Make changes to edit and delete to access a patient in the list using ic number instead of patient index. Update User Guide to reflect these changes to edit and delete commands.
Let's modify User Guide to ensure an easy tutorial for the users

Modify User Guide to include Edit and Delete Features

---

build.gradle
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/patient/UniquePatientList.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/model/ModelManagerTest.java

Fixed bugs for DeleteCommand and Edit command and update add command to check for existing ic number
---
1. create getCurrentPatientList method in ModelManager.java to get list of current patients
instead of using the getFilteredPatientList
1. Created isPatientWithIcNumberPresent method which checks if there is an existing patient with that ic number
2. Updated the AddCommandTest to test this method

Update Add command to check for existing Ic Number

---

docs/DeveloperGuide.md

Update Implementation of edit record feature into DG
---
1. First part of implementation of Record feature

Update DG with Record Feature

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AssignCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/patient/Gender.java
src/main/java/seedu/address/model/patient/Patient.java
src/main/java/seedu/address/model/patient/Priority.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPatient.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/model/patient/GenderTest.java
src/test/java/seedu/address/model/patient/PriorityTest.java
src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
src/test/java/seedu/address/testutil/PatientBuilder.java
src/test/java/seedu/address/testutil/TypicalPatients.java

---
1. Created Priority class
2. Created PriorityTest class
1. Edited Patient Class and all relevant classes to integrate Priority

Add and implement Priority attribute

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/RecordCommandParser.java
src/main/java/seedu/address/model/patient/Birthday.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/commands/RecordCommandTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/RecordCommandParserTest.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/model/patient/DepartmentTest.java
src/test/java/seedu/address/model/patient/PatientTest.java
src/test/java/seedu/address/model/patient/PriorityTest.java
src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
src/test/java/seedu/address/testutil/PatientUtil.java

---
1. Fixed various test cases (but not all)
1. Added on to some of the existing test cases
1. Minor fixes such as Messages not displaying Priority & Birthday giving wrong intended String in toString, etc.

Fix & Add Test Cases

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/commands/RecordCommandTest.java
src/test/java/seedu/address/logic/commands/ViewCommandTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java

Fix failing test cases for Edit command related code
---
1. Created `createEditPatientDescriptor` method to abstract away the EditPatientDescriptor logic from `parse` function
1. Improved testing by adding new test cases

Update Edit command related tests

---

src/main/java/seedu/address/logic/parser/AssignCommandParser.java
src/test/java/seedu/address/logic/commands/AssignCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/RecordCommandTest.java
src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
src/test/java/seedu/address/logic/parser/RecordCommandParserTest.java
src/test/java/seedu/address/model/patient/RecordTest.java
src/test/java/seedu/address/testutil/TypicalPatients.java

Create the basic testcases for AssignCommand
---
1. create test for AssignCommand
1. create test for AssignCommandParser

Create test for Assign Command feature

---

src/main/java/seedu/address/logic/commands/AssignCommand.java
src/main/java/seedu/address/logic/commands/Command.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/RecordCommand.java
src/main/java/seedu/address/logic/commands/RedoCommand.java
src/main/java/seedu/address/logic/commands/UndoCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/VersionedAddressBook.java
src/main/java/seedu/address/model/patient/Record.java
src/main/java/seedu/address/ui/RecordCard.java

1. Wrapped the values in Record class with SimpleStringProperty so that they can be observed by GUI observers
2. Added components in RecordCard as observers of these values so that they can update when the values change
3. Fix some checkstyle issues

Fix bug whereby UI does not update with new Record field values when record is edited

---

docs/UserGuide.md

Update UserGuide.md to allow user to download latest release
---
1. Update UserGuide.md to allow user to download latest release in the quick start section

Update UserGuide.md to allow user to download latest release

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/model/patient/Record.java
src/test/java/seedu/address/logic/LogicManagerTest.java

Currently, there are some failing test cases. Debug Record and other classes to pass these test cases.

Fix failing test cases

---

docs/AboutUs.md
docs/DeveloperGuide.md
docs/SettingUp.md
docs/_markbind/layouts/default.md
docs/team/aaronjt1.md
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
src/test/java/seedu/address/model/patient/PatientWithIcNumberPredicateTest.java

Fixing error message bugs and updating PPP
---
1. Update the error message accordingly
1. Fix bug which caused no error message for Ic number
1. Added relevant components for PPP

Branch fix add bugs

---

docs/team/wujy28.md
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AssignCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AssignCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java

Fixed an error message bug in AssignCommand and updated PPP
---
1. Fixed an error message bug in AssignCommand whereby no error message is shown when department prefix is not present
2. Updated PPP draft

Fixed error message bug for assign command and updated PPP

---

docs/DeveloperGuide.md
docs/team/thienmy0.md
src/main/java/seedu/address/logic/commands/RecordCommand.java

Update PPP and DG
---
1. Rough draft updates
1. Updated Appendix: Instructions for Manual Testing

Update PPP and DG Appendix Instructions for Manual Testing

---

docs/DeveloperGuide.md
docs/team/aaronjt1.md

Update use cases in developer guide
---
1. change the use cases to new product

Update use cases in DeveloperGuide

---

docs/DeveloperGuide.md
docs/UserGuide.md

Update Data Archiving Section in Developer Guide
- Added an update to the Data Archiving section of the Developer Guide. This enhancement provides a detailed overview of the data archiving process, including its implementation strategy, storage, and example.

Update Data Archiving Section in Developer Guide

---

docs/diagrams/DeleteSequenceDiagram.puml
docs/diagrams/EditSequenceDiagram.puml
docs/diagrams/RedoSequenceDiagram.puml
docs/diagrams/UndoRedoState0.puml
docs/diagrams/UndoRedoState1.puml
docs/diagrams/UndoRedoState2.puml
docs/diagrams/UndoRedoState3.puml
docs/diagrams/UndoRedoState4.puml
docs/diagrams/UndoRedoState5.puml

Make modifications to Delete sequence diagram, and undo & redo state diagrams. Also implemented Redo, Edit sequence diagrams.

Add UML diagrams

---

docs/UserGuide.md

Modified features and added hyperlinks to increase readability of the user guide

Modify features in User Guide

---

docs/team/aaronjt1.md
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java

Update PPP to hit page length and improve testing
---
1. Reduced some components to reduce PPP
1. Improve test coverage for AddressBookParser and AssignCommand

Improve test coverage

---

docs/DeveloperGuide.md
docs/diagrams/StorageClassDiagram.puml

Update the class in `Storage` diagram.
- Added `JsonAdaptedRecord` into `Storage` diagram.

Update Storage diagram in DG

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/diagrams/RecordCommandParserActivityDiagram.puml
docs/diagrams/RecordSequenceDiagram.puml
docs/team/thienmy0.md

Fix UG bugs and update DG diagrams
---
1. Table of contents & Command Summary
2. Fix bugs
1. Update record sequence diagram
2. Add record activity diagram

Fix UG Bugs & Update DG Diagrams

---

docs/DeveloperGuide.md
docs/diagrams/UndoRedoState0.puml
docs/diagrams/UndoRedoState1.puml

Minor modifications to the undo & redo features section in DeveloperGuide.md

Minor changes to DeveloperGuide.md

---

docs/DeveloperGuide.md
docs/team/thienmy0.md

Update PPP to fit 2 pages
Format DG from use cases onwards

Update PPP and Format DG

---

docs/DeveloperGuide.md

Considered potential design considerations under the Edit section of DeveloperGuide.md

Add design considerations under Edit feature

---

docs/team/aaronjt1.md

##Summary
Very minor update in PPP
Update the PPP pull requests reviewed section to display correct information

Update single line in PPP

---

docs/DeveloperGuide.md
docs/UserGuide.md

Fix UG & DG Bugs

---

docs/team/riyamehta2211.md

Fix minor line spacing issues in PPP

Fix formatting issues in PPP
